#!/usr/bin/python
import socket
import sys
import re

file = open('lista.txt')
for linha in file.readlines():
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	s.connect((sys.argv[1], 25))
	resp = s.recv(1024)
	s.send("VRFY "+linha)
	resp = s.recv(1024)
	if re.search('252', resp): 
		print "Usuario encontrado:" +resp.strip('252 2.0.0')


#if len(sys.argv) != 3:
#	print "Use: python smtpenum.py IP usuario"
#	sys.exit(0)

#s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
#s.connect((sys.argv[1], 25))
#banner = s.recv(1024)
#print banner

#s.send("VRFY "+sys.argv[2]+"\r\n")
#r = s.recv(1024)
#print r
